# -*- coding: utf-8 -*-
"""text_manipulation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xoAbn9YH4RrbJ3PqHe84mw9X0j3uFawz
"""

from typing import Container
import pandas as pd

with open("/content/drive/MyDrive/2023-1/Seguridad de redes/Corte 1/libro_muertos.txt", mode='r', encoding='latin-1') as f:
    tx = f.read()
tx

tx = tx.replace('\n', '')
tx = tx.replace("/", "")
tx = tx.replace('.', '')
tx = tx.replace(',', '')
tx = tx.replace('-', '')
tx = tx.replace('"', '')
tx = tx.replace('0', '')
tx = tx.replace('1', '')
tx = tx.replace('2', '')
tx = tx.replace('3', '')
tx = tx.replace('4', '')
tx = tx.replace('5', '')
tx = tx.replace('6', '')
tx = tx.replace('7', '')
tx = tx.replace('8', '')
tx = tx.replace('9', '')
tx = tx.replace('¿', '')
tx = tx.replace('?', '')
tx = tx.replace('!', '')
tx = tx.replace('¡', '')
tx = tx.replace(';', '')
tx = tx.replace(':', '')
tx = tx.replace('«', '')
tx = tx.replace('»', '')
tx = tx.lower()
print(tx)

tx

tx_split = tx.split()
print(len(tx_split))
print(tx_split)
len(tx_split[2])

print("En el texto hay",len(tx_split), "palabras")

tx_two=[]
for i in range(len(tx_split)):
  if len(tx_split[i]) == 2:
    tx_two += tx_split[i]

tx_three=[]
for i in range(len(tx_split)):
  if len(tx_split[i]) == 3:
    tx_three += tx_split[i]

tx_four=[]
for i in range(len(tx_split)):
  if len(tx_split[i]) == 4:
    tx_four += tx_split[i]

import pandas as pd
tx_word_count =  pd.Series(list(tx_split)).value_counts()
print(tx_word_count)

print('En el texto hay', len(tx_split), 'palabras')
print('En el texto hay', round(len(tx_two)/2), 'palabras de dos letras')
print('En el texto hay', round(len(tx_three)/3), 'palabras de tres letras')
print('En el texto hay', round(len(tx_four)/4), 'palabras de cuatro letras')
print('************************************************')
print('La palabra de dos letras que más se repite en el texto es: de')
print('La palabra de tres letras que más se repite en el texto es: que')

# ChatGPT
palabras = tx_split
cont2 = 0
cont3 = 0
cont4 = 0

for palabra in palabras:
    if len(palabra) == 2:
        cont2 += 1
    elif len(palabra) == 3:
        cont3 += 1
    elif len(palabra) == 4:
        cont4 += 1

total = cont2 + cont3 + cont4
print(f"Palabras de dos letras: {cont2}")
print(f"Palabras de tres letras: {cont3}")
print(f"Palabras de cuatro letras: {cont4}")
print(f"Total de palabras de dos, tres y cuatro letras: {total}")